apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: sping-music
  description: spring-music
  tags:
    - app-accelerator
    - java
    - spring
    - web
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=sping-music'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
